CREATE TYPE medium_type AS ENUM ('In Person', 'Video Call', 'Phone Call', 'Text', 'Email', 'Letter', 'Other');

CREATE TABLE interactions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bondId INTEGER REFERENCES bonds(id),
  date TEXT NOT NULL,
  medium medium_type NOT NULL,
  location TEXT,
  description TEXT
);
